---
title: "BA-BINTV2006U  Programming and Data Analysis for Business: Exercise 1"
author: "by Felix Thomsen, Alexander Schiøtz, Anders Laurents, Bertram Hage"
date: "2024-10-01"
output: 
  html_document:
    theme: sandstone
    code_folding: show
---

## 1. Data
<!-- 1. Write a short section about your data and why it is interesting to work with this data. -->



## 2. Data structure
<!-- 2. Load the dataset into R and inspect its structure. How many rows, how many columns, what is the
summary statistics for the numeric variables? -->
```{r init, warning = FALSE, message=FALSE}
library(knitr)
library(markdown)
library(rmarkdown)
library(tidyverse)
library(lubridate)
library(readxl)
theme_set(theme_bw())
```
```{r}
# Add code here

1+1
# Bertram og Alexander er grimme
# Import csv
data <- read_csv("data.csv")
```


## 3. Data types
<!-- 3. What data types do your data contain? -->

## 4. New categorial variable
<!-- 4. Create a variable (new column) that categorizes the numeric variable as "High," "Medium," or
"Low". Use a conditional statement for this. -->
```{r}
# Add code here
```

## 5. Using a loop
<!-- 5. Use a loop to iterate through all rows and do the same task as in question 4, using conditions. -->
```{r}
# Add code here
```

## 6. Replace text
<!-- 6. Replace some text in one column with some other text -->
```{r}
# Add code here
```

## 7. Subset the data.frame
<!-- 7. Subset the data.frame with respect to one variable (categorical such as “region”, “gender” or “job-
sector”). (Hint: You will get an elegant way of solving it in week 40, but you do have tools to solve it
with the tools you’ve gotten so far) -->
```{r}
# Add code here
```

### 7.a. Number of instances
<!-- a. Count the number of instances (lines) from each category -->
```{r}
# Add code here
```

### 7.b. Mean
<!-- b. Calculate the mean of one on the numeric variables with respect to each category -->
```{r}
# Add code here
```

## 8. Reflection
<!-- 8. Use the results and your business knowledge to describe the situation. Including reflection on usage
of AI-tools. -->